# Site settings
title: beta.uy
slogan: Crafting the right products to solve real problems
email: hi@beta.uy
description: > # this means to ignore newlines until "baseurl:"
  A place to share our knowledge on engineering, design, and product-making
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://beta.uy" # the base hostname & protocol for your site
twitter_username: beta-uy
github_username:  beta-uy

# Build settings
markdown: kramdown
